[package]
name = "mpvy"
version = "0.1.0"
description = "Youtube audio player based on mpv"
repository = "https://github.com/kadircy/mpvy"
license = "MIT"
edition = "2021"

[dependencies]
dirs = "6.0.0"
